### PR TITLE
fix typo: mirco -> micro

### LINKED ISSUE #174: typo in ElectricPotential
`ElectricPotential` has a typo: 
def toMi**rc**ovolts = to(Microvolts). A PR is forthcoming.

### PR DESCRIPTION
**Pull request by derekmorr**
This fixes #174 .

### CODE REVIEW

**Comment by cquiroz** [comment]
Are there any docs with the typo?

**Comment by derekmorr** [comment]
None I can find. I grepped through the code base.

**Comment by cquiroz** [comment]
I guess this is an `API breaking` change. I wonder how should we handle this version-wise. It seems too small a change to call it a version `2.0`

**Comment by derekmorr** [comment]
Do we just put a note in the release notes alerting users to the incompatibility? I agree this is far too trivial for a major version bump.

**Comment by cquiroz** [comment]
Sounds fine to me

**Pull request merged**
