### PR TITLE
Prepare for release 1.0

### PR DESCRIPTION
**Pull request by cquiroz**
Update the build file and README for release 1.0

Note we should update the public documentation and wiki as well.

### CODE REVIEW

**Comment by vitorsvieira** [comment]
What you guys think about removing 2.10.6 option from the build?

**Comment by derekmorr** [comment]
Assuming everything still works on 2.10, I don't see a reason to remove it. Are there changes we want to make that aren't backwards compatible with 2.10?

**Comment by cquiroz** [comment]
What's the benefit of removing 2.10, The 2.10 line is still being used in many places

**Comment by vitorsvieira** [comment]
No pros and cons on my side, just wanted to hear your opinion as I see other libraries dropping this option.

**Comment by derekmorr** [comment]
Assuming Travis returns OK, this LGTM.

**Comment by darkfrog26** [comment]
That's odd.  It says I'm not authorized to merge the pull request...

**Comment by derekmorr** [comment]
I'm getting the same error. I'm wondering if it's b/c the repo is under the typelevel organization now?

**Comment by darkfrog26** [comment]
It shouldn't be. I have merged PRs since the change happened.  I think it has to do with `master` being a protected branch now?

**Comment by cquiroz** [comment]
Maybe I tightened the permissions too much. Can you try again?

**Comment by darkfrog26** [comment]
@cquiroz yep, that fixed it. :)

**Pull request merged**
