### PR TITLE
Prepare for release 1.2.0

### PR DESCRIPTION
**Pull request by cquiroz**
Note that the main README was generated via tut

### CODE REVIEW

**Comment by derekmorr** [comment]
Looks good to me. 

I'm assuming we decided not to do #184 ? If so I'll close that issue.

**Comment by cquiroz** [comment]
I don't know about #184

**Comment by derekmorr** [comment]
I'm leaning towards not opening it. The motivation for it was releasing pureconfig-squants, which was done without opening it. I don't like that its input it `Any`, and it exposes internal machinery we may not want opened.

**Comment by derekmorr** [comment]
Which reminds me, we should add a note about pureconfig-squants to the README.

**Comment by cquiroz** [comment]
Do you want to add that to the README in tut?

**Comment by derekmorr** [comment]
Sure. Do you want me to add it to this PR or merge this one and make a new one ?

**Comment by cquiroz** [comment]
either way is ok for me

**Comment by derekmorr** [comment]
I can't access this PR since it's in your repo. I'll merge it, then add.

**Pull request merged**
