### PR TITLE
add ElectricCurrentDensity and MagneticFieldStrength types

### PR DESCRIPTION
**Pull request by underscorenico**
3rd PR concerning #252 .
This PR assesses unimplemented methods in ElectricCurrent and adds needed types.

### CODE REVIEW

**Comment by derekmorr** [comment]
Could you be sure to update the `ImplicitDimension` object with this?

**Comment by underscorenico** [comment]
Oh sorry, I did it again

**Comment by underscorenico** [comment]
Done!
I also added ElectricCurrent, which was missing

**Comment by derekmorr** [comment]
Thanks! I'll take a look at these over the weekend.

**Comment by underscorenico** [comment]
Corrected unit names, added "per". Symbol is now val instead of def

**Pull request merged**
