### PR TITLE
add SiUnit marker trait to SI units in electro package

### PR DESCRIPTION
**Pull request by derekmorr**
This will help #215 .

### CODE REVIEW

**Comment by cquiroz** [comment]
A general question, why `SiUnits` instead of `SIUnits`? SI is an acronym right?

**Comment by derekmorr** [comment]
It is, but `SiUnit` already existed. If we rename it, we break compatibility. 

I don't have strong opinions about it, but, personally, I find `SiUnit` easier to read than `SIUnit` (although that's entirely subjective).

**Comment by cquiroz** [comment]
Is the change in #215 big enough to break compatibility?

**Comment by cquiroz** [comment]
Now I understand how this didn't break the build `SiUnit` is already present. I don't think there is a need to change it if already present with that name

**Comment by derekmorr** [comment]
Right. The `SiUnit` trait already existed. It was inconsistently applied to various units. I'm adding it to units where appropriate, so I can more easily group them together (in #215).

#215 should only add new capabilities. It doesn't change anything.

**Comment by cquiroz** [comment]
Allright, that sounds perfectly fine

**Pull request merged**
