### PR TITLE
Permeability

### PR DESCRIPTION
**Pull request by cquiroz**
While looking at the universal constants #257 I realized that we don't have a definition for `Permeability`. This PR adds this new `Quantity`

### CODE REVIEW

**Comment by underscorenico** [comment]
Maybe we should standardize what to do with "symbol". In some clases it is a `val`, in others it is a `def`.
@cquiroz @derekmorr

**Comment by cquiroz** [comment]
@underscorenico That's a good observation. I'd venture to say that in most cases a `val` is appropriate. I'll change the code to reflect that

**Comment by underscorenico** [comment]
@cquiroz I was thinking that you could also implement the `/` method in `Inductance`, which returns `Permeability`.

**Comment by cquiroz** [comment]
@underscorenico Good suggestion, I added the division and also added multiplication to `Permeability` to get `Inductance`

**Comment by cquiroz** [comment]
How can we move forward on this and the other pending PRs?

**Pull request merged**
