### PR TITLE
Allow currency parsing from implicit context

### PR DESCRIPTION
**Pull request by belerophon**
This PR adds a companion object to `Currency` whose `apply` receives a currency code String, an implicit `MoneyContext` and returns a `Try[Currency]`.

It also changes the methods in `Money` companion that used to parse a currency from a String and relied solely on the `defaultMoneyContext`  to fetch the corresponding `Currency` value:  these methods now receive an implicit `MoneyContext` and use the new `Currency.apply` which, I think, should solve #296.

For my use case, these modifications are useful when working with domain models that specify some `Currency`, that must be parsed from JSON, and when loading `Currency` from typesafe config (using PureConfig).

### CODE REVIEW

**Comment by belerophon** [comment]
It looks like I missed this #305 before creating this PR.
Sorry about this.

The comment there:
> I'm not sure about this, passing this as an implicit sounds like an overstretch of implicit. Wouldn't you rather pass it as a plain param?

I agree with @estsauver when he says that the expected usage would be to have the context passed implicitily. Either way, I think the most important point would be to stop using the default context on those operations.

Hope to hear some input on this.
Thanks!

**Comment by belerophon** [comment]
Hi there,
Did someone have the opportunity to take a look into this PR?

**Comment by psttf** [comment]
@garyKeorkunian I've checked the current master (with this PR merged) and it seems like #323 is still a problem.

**Comment by jchapuis** [comment]
Also getting that #323 when running tests

**Pull request merged**
