### PR TITLE
Add VolumeFlow units (l,nl,ml,µl per s,min,h,d)

### PR DESCRIPTION
**Pull request by yangchoo**
Adds units ranging from nano, milli, micro prefixes for litre for a
range of second, minute, hour, days units.

### CODE REVIEW

**Comment by yangchoo** [comment]
We're currently using some combination of these units internally. Decided to generalize the range across all time units.

**Comment by yangchoo** [comment]
@cquiroz 
I'm having issues trying to debug a seemingly unrelated error that's occurring for this PR only in the JDK11/Scala 2.13.1 environment. The tests which I've touched are all executing fine and the error is from a call to squantsJS.

Here's the relevant trace:
```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f3119edcb41, pid=4974, tid=4985
#
# JRE version: OpenJDK Runtime Environment (11.0.2+9) (build 11.0.2+9)
# Java VM: OpenJDK 64-Bit Server VM (11.0.2+9, mixed mode, tiered, compressed oops, g1 gc, linux-amd64)
# Problematic frame:
# V  [libjvm.so+0xbceb41]  Node::add_req(Node*)+0xc1
#
# Core dump will be written. Default location: Core dumps may be processed with "/usr/share/apport/apport %p %s %c %d %P" (or dumping to /home/travis/build/typelevel/squants/core.4974)
#
# An error report file with more information is saved as:
# /home/travis/build/typelevel/squants/hs_err_pid4974.log
#
# Compiler replay data is saved as:
# /home/travis/build/typelevel/squants/replay_pid4974.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
#
/usr/local/bin/sbt: line 233:  4974 Aborted                 (core dumped) "$@"
The command "sbt ++$TRAVIS_SCALA_VERSION squantsJVM/compile squantsJS/compile squantsJS/fastOptJS" exited with 134.
```

I'm happy to help look into it if you could post the error file or if you have any thoughts on why this may be happening.

Thanks!

**Comment by cquiroz** [comment]
I've seen this several times. I'd rather move to use Github Actions as #375

**Comment by cquiroz** [comment]
This is running on GHA, we should review it

**Comment by yangchoo** [comment]
Great to see that its running fine on GHA. Thanks for the merge commit.

Let me know if there's anything else that's required from me.

**Pull request merged**
